name: map container images

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions: 
            security-events: write
            contents: read
            id-token: write
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.8'
        - name: ACR login
          uses: Azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - name: Build and push docker image
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ${{ secrets.IMAGE_TAG }}
            file: Dockerfile
        # Run devops analysis
        - name: Run MDO analysis
          uses: microsoft/security-devops-action@latest
          id: msdo
          with:
            include-tools: container-mapping
          